apiVersion: v1
kind: Pod
metadata:
  name: aurora-admin-check
  namespace: deduction
  labels:
    role: db-admin
spec:
  serviceAccountName: redemption-sa
  containers:
  - name: admin-tools
    image: alpine/psql:18.4
    command: ["/bin/sh", "-c"]
    args:
      - |
        set -e

        apk add --no-cache aws-cli jq
        sleep 1

        export SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $SECRET_ID --query SecretString --output text)
        sleep 1
        export PGUSER=$(echo $SECRET_JSON | jq -r .username)
        export PGPASSWORD=$(echo $SECRET_JSON | jq -r .password)

        psql -U "$PGUSER" -h "$PGHOST" << 'EOF'
        SELECT * FROM loyalty_accounts WHERE points_balance < 50000;
        EOF

    env:
      - name: PGHOST
        value: "${PGHOST}"
      - name: PGPORT
        value: "5432"
      - name: PGDATABASE
        value: "postgres"
      - name: SECRET_ID
        value: "${SECRET_ID}"
  restartPolicy: Never