apiVersion: v1
kind: ConfigMap
metadata:
  name: redemption-scripts
  namespace: deduction
data:
  # ---------------------------------------------------------
  # FRONTEND (K8S API): Receives HTTP, sends to SQS
  # ---------------------------------------------------------
  api.py: |
    import boto3, os, json
    from fastapi import FastAPI
    from botocore.config import Config
    app = FastAPI()
    QUEUE_URL = os.environ['QUEUE_URL']

    my_config = Config(
        max_pool_connections=100,
        retries={'max_attempts': 3}
    )
    sqs = boto3.client('sqs', region_name='eu-west-1', config=my_config)

    @app.post("/redeem")
    def redeem_points(payload: dict):
        sqs.send_message(QueueUrl=QUEUE_URL, MessageBody=json.dumps(payload))
        return {"status": "202 Accepted", "message": "Redemption in progress"}

  # ---------------------------------------------------------
  # BACKEND (WORKER): Polls SQS, updates Aurora DB
  # ---------------------------------------------------------
  worker.sh: |
    #!/bin/bash
    echo "Starting Redemption Worker. Fetching Aurora credentials..."
    SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $SECRET_ID --query SecretString --output text)
    export PGUSER=$(echo $SECRET_JSON | jq -r .username)
    export PGPASSWORD=$(echo $SECRET_JSON | jq -r .password)

    echo "Connected! Listening to SQS queue..."
    while true; do
      MSG=$(aws sqs receive-message --queue-url $QUEUE_URL --wait-time-seconds 5 --max-number-of-messages 1)
      if [ ! -z "$MSG" ] && [ "$MSG" != "null" ]; then
        RECEIPT=$(echo $MSG | jq -r '.Messages[0].ReceiptHandle')
        EMAIL=$(echo $MSG | jq -r '.Messages[0].Body' | jq -r '.email')

        echo "Processing redemption for: $EMAIL"
        psql -h $PGHOST -d postgres -c "UPDATE loyalty_accounts SET points_balance = points_balance - 500 WHERE email = '$EMAIL' AND points_balance >= 500;"
        aws sqs delete-message --queue-url $QUEUE_URL --receipt-handle $RECEIPT
        echo "Message successfully processed and deleted."
      fi
    done
---
# INTERNAL SERVICE TO EXPOSE THE API
apiVersion: v1
kind: Service
metadata:
  name: redemption-api-internal
  namespace: deduction
spec:
  ports:
    - port: 8080
      targetPort: 8000
  selector:
    app: redemption-api
---